baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "6 octobre 2023"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    - schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: " Billetterie "
  #  link: "https://www.billetweb.fr/devfest-perros-guirec"

  # The Press Link in the menu
  # If you don't want this, just comment the press property.
  #Press:
  #  text: "Dossier de Presse"
  #  link: "./doc/DevFest-Perros-Guirec.pdf"

  # List of Sponsors
  Sponsors:
    - name: "DCbrain"
      logo: "/img/partners/dcbrain.png"
      url: "https://dcbrain.com/"
    
    - name: "Eco-Compteur"
      logo: "/img/partners/ecocompteur.png"
      url: "https://www.eco-compteur.com/"

  # List of Partners
  Partners:
    - name: "Anticipa"
      logo: "/img/partners/anticipa.png"
      url: "https://www.technopole-anticipa.com/french-tech-lannion/"

  Speakers:
    - name: "Tugdual Grall"
      ref: "tugdual"
      photo: "/img/speakers/tugdual.jpg"
      bio: "Tugdual Grall, est Solutions Engineer chez GitHub, où il accompagne les développeurs dans leur utilisation de GitHub et des pratiques DevOps/DevSecOps.<br>
      Avant de travailler chez GitHub, 'Tug', était, DevRel chez Redis, Directeur du Product Management chez Red Hat, Technical Evangelist chez MapR, MongoDB et Couchbase. Tug a également travaillé comme CTO chez eXo Platform, et comme Product Manager et Développeur sur la platform JavaEE d'Oracle.<br>
      Tugdual est également co-fondateur du Nantes JUG (Java Users Group) qui réunit tous les mois depuis 2008 les développeurs et architectes de la région nantaise."
      company: "GitHub"
    - name: "Julien Salvi"
      ref: "julien"
      photo: "/img/speakers/julien.png"
      bio: "Into the Android world for 10 years, I experienced California the startup way of life before coming back to France. I am currently a Lead Android Engineer at Aircall where we are building the best phone system for modern businesses. Alongside Android, I have a great interest in backend development with Kotlin and AR/VR technology. In 2021, I became an Android GDE to continue my journey to always share and learn with the Android community. On my spare time, I am a world traveler and a beer lover always looking for the best IPAs!"
      company: "Aircall"
    - name: "Eléa Petton"
      ref: "elea"
      photo: "/img/speakers/elea.jpg"
      bio: "Etudiante pendant cinq ans à l'école d'ingénieurs ISEN Brest, je suis diplômée en octobre 2022 en tant qu'ingénieur généraliste avec une coloration Intelligence Artificielle (IA).<br>
      L'IA est un domaine qui me passionne et dans lequel je me spécialise en intégrant la TEAM AI Solutions d'OVHcloud en tant que Machine Learning Engineer.<br>
      Je travaille sur trois produits d'OVHcloud dédiés à l'entraînement et au déploiement de modèles d'IA : AI Training, AI Notebooks et AI Deploy. Mon rôle est de créer des verticaux sur ces produits sous différents formats pour les utilisateurs de la plateforme."
      company: "OVHcloud"
    - name: "Stephane Cauchy"
      ref: "stephane"
      photo: "/img/speakers/stephane.jpg"
      bio: "Host leader du Laboratoire d’expérimentation digitale (LED) de BPCE-SI, incubateur sur les nouveaux usages, pratiques et outils au service d’une édition logicielle toujours plus performante. Auteur du livre 'Etre agile par nature' qui retrace les débuts de la transformation agile chez BPCE. Près de 40 ans d'expérience, spécialiste de l'agilité d'entreprise et coach d'organisation."
      company: "BPCE-SI"
    - name: "LIU Yung"
      ref: "liu"
      photo: "/img/speakers/liu.jpg"
      bio: "Directeur délégué - Responsable de domaine STS (SOLUTIONS TECHNOLOGIQUES DU SI )"
      company: "BPCE-SI"
    - name: "Thomas Fournaise"
      ref: "thomas"
      photo: "/img/speakers/thomas.jpg"
      bio: "Passionné d'informatique et de développement depuis longtemps, je suis passé par les équipes projets, l'architecture et l'urbanisme d'entreprise avant de bifurquer vers l'IA et la Data. Je me passionne pour tous les sujets liés aux données, aux biais, à l'IA et à l'éthique. Depuis 2016, j'organise le Salon de la Data à Nantes."
      company: "Nickel"
    - name: "Julie Rabette"
      ref: "julie"
      photo: "/img/speakers/julie.jpg"
      bio: "Apres plus de 10 ans a alterner les missions de dev Java et de test, j'ai eu la chance de faire partie des premieres personnes a Nokia Lannion.<br>
      A travailler sur le remplacement d'algo 'classique' de la couche L1 de la 5G par du deepLearning en vue de l'integration sur accelerateur HW ML specific.<br>
      Depuis novembre nous avons pour objectif d'ameliorer les performances et nous travaillons sur la mise en place de la QAT sur le model.<br>"
      company: "Nokia"
    - name: "Alexandre Lou"
      ref: "alexandre"
      photo: "/img/speakers/alexandre.jpg"
      bio: "Aujourd'hui ingénieur MLOps chez Nokia, j'ai commencé en tant que stagiaire sur des problématiques Machine learning. Dans la continuité de ces travaux, je contribue à la création d'environnements dédiés aux projets"
      company: "Nokia"
    - name: "Renaud Allioux"
      ref: "renaud"
      photo: "/img/speakers/renaud.png"
      bio: "Co Founder, Chief Innovation and Future technologies @Preligens"
      company: "Preligens"

  # The entire schedule
  Schedule:
    - name: "Renaud Allioux"
      company: "Preligens"
      speakers:
        - name: "Renaud Allioux"
          ref: "renaud"
          photo: "/img/speakers/renaud.png"
      presentation:
        title: "Les développeurs à l'heure de l'IA"
        description: "Si l'actualité récente met en valeur certaine rupture autour des large langages models, 
        les évolutions technologiques liées à l'IA ont changé en continue le métier de développeur depuis plusieurs années. 
        Que ce soit travailler grâce à l'IA ou travailler pour faire de l'A les développeur.e.s sont plus que jamais au cœur de la machine.
        Sans ingénierie informatique la science de la donnée et la recherche en IA n'est que du concept et du PoC.
        Comment va évoluer le métier ? Impossible à dire, mais nous pouvons déjà analyser les changements des dernières années et essayer d'en tirer quelques conclusions."
    - name: "Tugdual Grall"
      company: "Github"
      speakers:
        - name: "Tugdual Grall"
          ref: "tugdual"
          photo: "/img/speakers/tugdual.jpg"
      presentation:
        title: "Copilot : L’intelligence artificielle au service des développeurs"
        description: "Amis développeurs, vous avez besoin:<br>
        <ul>
        <li>- d’écrire des tests pour vos applications Web/JavaScript ?</li>
        <li>- de compléter une classe Java d’accès aux données ?</li>
        <li>- corriger des bugs dans votre code ?</li>
        <li>- d’ajouter des nouveaux services à votre déploiement Kubernetes, Terraform ?</li>
        <li>- de comprendre du code que vous découvrez en arrivant sur un nouveau projet ?</li>
        </ul>
        Venez découvrir comment GitHub Copilot va vous aider sur ses taches et bien d'autres, et ce directement dans votre IDE favori, et quelque soit votre language de predilection! GitHub Copilot est un outil basé sur le maintenant très connu modèle OpenAI GPT.<br>
        Cette présentation s'appuie principalement sur des démonstrations durant lesquelles Tug montre comment il utilise GitHub Copilot pour développer le site https://windr.org . Venez également avec vos questions & retour d'experience si vous utilisez aujourd'hui Copilot: cette session sera interactive!<br>
        Tug couvrira également GitHub Copilot X, la vision de GitHub de l'IA et le travaille du développeur."
    - name: "Julien Salvi"
      company: "Aircall"
      speakers:
        - name: "Julien Salvi"
          ref: "julien"
          photo: "/img/speakers/julien.png"
      presentation:
        title: "Machine Learning sur Android avec ML Kit (sans être expert en IA)"
        description: "Et si je vous disais que vous n'avez pas besoin d'être un.e expert.e en intelligence artificielle ou en machine learning pour apporter certaines de ces fonctionnalités dans vos applications Android.<br>
        Dans cette session, nous explorerons ce que ML Kit a à offrir pour ajouter assez facilement des fonctionnalités de machine learning optimisées pour le mobile. En se basant sur des examples de code, nous explorerons les principales API de Vision et Natural Language pour potentiellement débloquer de nouvelles idées dans vos applications."
    - name: "Eléa Petton"
      company: "OVHcloud"
      speakers:
        - name: "Eléa Petton"
          ref: "elea"
          photo: "/img/speakers/elea.jpg"
      presentation:
        title: "A quel point devons-nous optimiser nos modèles d'IA ? Testons, évaluons, comparons !"
        description: "Dans le domaine du Machine Learning, le concept d'optimisation est au coeur de la création des modèles. Il existe de multiples façons d'optimiser un modèle d'IA en se basant sur divers aspects : précision, performance, explicabilité, latence, consommation énergétique, ...<br>
        Durant ce talk nous allons tout d'abord voir pourquoi il est primordial d'optimiser un modèle et quels sont les différentes optimisations possibles. Comment ? Au travers d'un cas d'usage métier pour voir à quel point notre modèle de Machine Learning peut être optimisé.<br>
        Dans un premier temps, nous nous intéresserons à la métrique 'phare' : la précision du modèle. En tant que Data Scientist, l'entraînement est notre première étape pour optimiser un modèle de Machine Learning.<br>
        Au delà de qualité et de la précision du modèle, il est primordial que ce dernier soit utilisable et déployable en production. Nous devons donc porter attention au temps d'exécution en évaluant à la fois la latence et l'intérêt métier. Pour cela, quoi de mieux que de créer un benchmark en se basant sur un jeu de données de test ?<br>
        Nous serons également attentifs à la complexité du modèle et à son explicabilité en nous intéressant au cas d'usage métier.<br>
        Ce talk montrera également l'impact écologique des modèles. Nous verrons comment évaluer leur émission de CO2 ou encore leur consommation énergétique.<br>
        Mais au final, devons nous tenir comptes de toutes ces métriques ?"
    - name: "Stephane Cauchy"
      company: "BPCE-SI"
      speakers:
        - name: "Stephane Cauchy"
          ref: "stephane"
          photo: "/img/speakers/stephane.jpg"
        - name: "LIU Yung"
          ref: "liu"
          photo: "/img/speakers/liu.jpg"
      presentation:
        title: "Le développeur augmenté chez BPCE année 1"
        description: "Octobre 2022, lors du précédent devfest nous découvrons l'IA générative et GPT3. Plein d'enthousiasme, nous retournons au bureau avec l'intuition qu'une révolution était en marche et que nous devions monter dans le train. Octobre 2023, 1 an après des résultats visibles : <br>
        <ul>
        <li>- les développeurs BPCE SI font du pair programming au quotidien</li>
        <li>- Des analystes utilisent un chatbot pour connaître le fonctionnement du SI</li>
        <li>- Les opérations lourdes de migration de code sont facilitées</li>
        </ul>
        Nous sommes aujourd'hui collectivement convaincu que nous vivons le début d'une transformation significative de nos métiers . Nous souhaitons vous raconter le chemin parcouru en 1 an pour revisiter les méthodes de travail de 2.600 personnes."
    - name: "Thomas Fournaise"
      company: "Nickel"
      speakers:
        - name: "Thomas Fournaise"
          ref: "thomas"
          photo: "/img/speakers/thomas.jpg"
      presentation:
        title: "Faut-il réguler les algorithmes ? Clairement non !"
        description: "L'intelligence artificielle est de plus en plus présente à nos cotés pour nous aider à prendre des décisions mais régulièrement on entend dire qu'elles prend de mauvaises décisions ou qu'elle est sont biaisée. La solution qui est souvent évoquée est de réguler les algorithmes. Mais qu'est ce que cela veut dire et est ce réellement la bonne solution ? Plongeons ensemble dans les biais liés aux données et aux algorithmes, regardons ce que propose l'IA Act ou la directive sur la responsabilité des IAs et essayons de voir quel rôle ont les développeurs pour faire de meilleures intelligences."
    - name: "Julie Rabette"
      company: "Nokia"
      speakers:
        - name: "Julie Rabette"
          ref: "julie"
          photo: "/img/speakers/julie.jpg"
        - name: "Alexandre Lou"
          ref: "alexandre"
          photo: "/img/speakers/alexandre.jpg"
      presentation:
        title: "Kubeflow pour le MLOps avec Cas d'usage"
        description: "Le MLOps, contraction de Machine Learning Operations, désigne l'ensemble des pratiques mises en œuvre pour automatiser l'entrainement, le déploiement et la maintenance de modèles de machine learning. Ces pratiques permettent
        notamment de traiter les problématiques de gestion des versions de modèles, de gestion de ressources cloud, ou encore de monitoring.<br>
        Ceci nécessite un environnement dédié au ML : une plateforme MLOps. L'automatisation des tâches répétitives et des pipelines permet aux équipes de se concentrer sur l'optimisation des performances des modèles ou l'exploration
        des données. Kubeflow est une plateforme MLOps qui vise à centraliser les outils ML pour le training, l'optimisation d'hyperparamètres et bien d'autres atouts qui seront présentés durant ce talk."
