baseurl: "https://devfest.codedarmor.fr/"
title: "DevFest Perros"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "DevFest Perros-Guirec"
  Description: "sur de la côte de granit rose"
  Date: "6 octobre 2023"
  Price: "30€"
  Venue: "Palais des Congrès"
  Address: "1 Rue du Maréchal Foch"
  City:  "Perros-Guirec"
  State: "France"
  Images: ["/img/cover.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    #- speakers
    #- schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "A propos"
    location: "Location"
    speakers: "Speakers"
    schedule: "Programme"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: " Billetterie "
  #  link: "https://www.billetweb.fr/devfest-perros-guirec"

  # The Press Link in the menu
  # If you don't want this, just comment the press property.
  #Press:
  #  text: "Dossier de Presse"
  #  link: "./doc/DevFest-Perros-Guirec.pdf"

  # List of Sponsors
  Sponsors:
    - name: "DCbrain"
      logo: "/img/partners/dcbrain.png"
      url: "https://dcbrain.com/"
    
    - name: "Eco-Compteur"
      logo: "/img/partners/ecocompteur.png"
      url: "https://www.eco-compteur.com/"

  # List of Partners
  Partners:
    - name: "Anticipa"
      logo: "/img/partners/anticipa.png"
      url: "https://www.technopole-anticipa.com/french-tech-lannion/"

  Speakers:
    - name: "Héloïse Dano"
      ref: "heloise"
      photo: "/img/speakers/heloise.jpg"
      bio: "Avec sa société ecologeek, Héloïse tente d'initier le plus de personnes possible aux pratiques du Numérique Responsable. Fervente partisane de l'utilisation de l'intelligence collective elle utilise au maximum des méthodes participatives et collaborative pour faire comprendre les messages clés tout en passant un bon moment. Elle est également membre du CA de l'association de la Fresque Du Numérique et participe activement à de nombreux collectifs et groupes de travail autour de ce sujet. Bretonne depuis toujours elle a à coeur de développer un réseau local pour parler du Numérique Responsable jusqu'au fin fond du Finistère ;)"
      company: "Ecologeek"
    - name: "Olivier Le Goaër"
      ref: "olivier"
      photo: "/img/speakers/olivier.png"
      bio: "Titulaire d'un Doctorat en Informatique de l'Université de Nantes, Olivier Le Goaër est actuellement enseignant-chercheur à l'Université de Pau et des Pays de l'Adour. Son thème de recherche est le Génie Logiciel (Vert). Il est responsable scientifique de la branche Mobile (Android et bientôt iOS) du projet Open Source ecoCode, basé sur SonarQube. Il milite pour l'introduction du Numérique Responsable dans les formations universitaires et d'ingénieurs en Informatique."
      company: "Université de Pau et des Pays de l'Adour"
    - name: "Tristan Nitot"
      ref: "tristan"
      photo: "/img/speakers/tristan.png"
      bio: "Je suis un passionné du numérique de la première heure. Ingénieur, entrepreneur du numérique, auteur, co-fondateur et ex-président de Mozilla Europe (Firefox), co-fondateur d'Unsearch et animateur du podcast l'Octet Vert sur le numérique et le climat. Je viens de rejoindre Scaleway (fournisseur de cloud français) en tant que responsable du développement durable."
      company: "Scaleway"
    - name: "Romuald Priol"
      ref: "romuald"
      photo: "/img/speakers/romuald.jpg"
      bio: "Passionné d’écologie, de good-tech, d’éthique et de performance informatique, je suis développeur expert en web-performance au quotidien, représentant du collectif numérique responsable de GreenIt.fr et ambassadeur formation chez thegreencompagnon. J’essaye de promouvoir l’évolution du numérique en le rendant responsable : pour un numérique plus « green », plus « performant », plus « éthique » et plus « accessible »."
      company: ""
    - name: "Sylvain Revereault"
      ref: "sylvain"
      photo: "/img/speakers/sylvain.jpg"
      bio: "Travaillant depuis une vingtaine d’années dans l’informatique, je me suis progressivement spécialisé dans les technologies systèmes et réseaux, en particulier autour des systèmes GNU/Linux, avant de m’orienter vers les thématiques DevOps et de l'agilité dans le monde “Ops”. En complément des facettes techniques, j'explore les aspects collaboratifs et les approches innovantes de management, et j'ai consacré ces deux dernières années à monter en compétences sur les liens de nos métiers avec l'écologie. Je suis actuellement consultant autour des thématiques DevOps, Management 3.0 et Green IT chez Zenika, tout en portant la casquette de CTO de l’agence de Rennes." 
      company: "Zenika"
    - name: "Olivier Ridoux"
      ref: "olivier_ridoux"
      photo: "img/speakers/olivier_ridoux.png"
      bio: "Je suis professeur à l’université de Rennes 1 (2 fois directeur de département, actuellement responsable de formation), chercheur à l’IRISA (1 fois responsable de département, créateur et responsable d’une équipe, aujourd’hui dissoute), et membre du groupe de travail CNRS ÉcoInfo. Mes centres d’intérêt vont vers la logique formelle et ses applications et les limites physiques du calcul."
      company: "IRISA"
    - name: "Pierre Rust"
      ref: "pierre"
      photo: "img/speakers/pierre.jpg"
      bio: "Développeur et chercheur chez Orange, je travaille sur l'empreinte environnementale du numérique et sur sa réduction."
      company: "Orange"


  # The entire schedule
  Schedule:
    - name: "Ouverture des portes"
      time: "8h45"
    - name: "Intro"
      time: "9h15"
    - name: "Héloïse Dano"
      company: "Héloïse Dano (Ecologeek)"
      speakers:
        - name: "Héloïse Dano"
          ref: "heloise"
          photo: "/img/speakers/heloise.jpg"
      presentation:
        title: "Numérique responsable"
        description: "Quels sont les impacts environnementaux, sociaux et sociétaux du numérique.? Le Numérique Responsable c’est quoi ? Comment il répond à ces problématiques ? Quelles sont les grandes pistes d'actions à notre échelle de dev ? On tentera de répondre ensemble à ces questions lors de cette conférence interactive. (Re)voir les bases pour aller dans la bonne direction ça fait pas de mal ;)"
        time: "9h30"
    - name: "Tristan Nitot"
      company: "Tristan Nitot (Scaleway)"
      speakers:
        - name: "Tristan Nitot"
          ref: "tristan"
          photo: "/img/speakers/tristan.png"
      presentation:
        title: ""
        description: "L'été 2022, avec sa sécheresse et ses multiples canicules en Europe, ses inondations au Pakistan nous permet de vivre le dérèglement climatique de près. Mais quels sont les rapports entre 
        le changement climatique et le numérique ? Ce dernier fait-il partie de la solution ou du problème ? Que peut-on faire personnellement et professionnellement à notre niveau ? Ce sont ces sujets qui seront 
        abordés successivement dans cete intervention."
        time: "10h30"
    - name: "Café"
      time: "11h15"
    - name: "Sylvain Revereault"
      company: "Sylvain Revereault (Zenika)"
      speakers:
        - name: "Sylvain Revereault"
          ref: "sylvain"
          photo: "/img/speakers/sylvain.jpg"
      presentation:
        title: "Impacts environnementaux du Cloud : the good, the bad, the ugly"
        description: "Le Cloud est un outil formidable qui facilite notre quotidien, nous permet de travailler plus vite, de mettre en place des architectures dont nous n'osions pas rêver il y a encore quelques années.

Parmi les promesses du Cloud, il y a celle du Green IT : en utilisant le Cloud, nous pourrions réduire l'empreinte environnementale de nos activités. Mais qu'en est-il réellement de cette promesse ?

C'est ce que nous explorerons lors de cette présentation, en nous penchant tout d'abord sur les impacts environnementaux de l'informatique au sens large, puis en nous focalisant sur les aspects hébergements, et enfin en regardant ce que les grands acteurs du Cloud mettent en place pour réduire leurs impacts."
        time: "11h30"
    - name: "Déjeuner"
      time: "12h15"
    - name: "Romuald Priol"
      company: "Romuald Priol (Association Green IT)"
      speakers:
        - name: "Romuald Priol"
          ref: "romuald"
          photo: "/img/speakers/romuald.jpg"
      presentation:
        title: "Numérique responsable : Comment lier performance et écologie ?"
        description: "Contrairement à ce que l'on pourrait croire, la performance n'est pas forcément \"green\", et ça n'est pas parce que vous avez de très bons scores sur les outils d'analyse de performance que votre application est écoconçue ! Nous allons voir comment développer une application de la façon \"responsable\" en comprenant les différents problèmes écologiques du numérique tout en passant en revue les bonnes (ou mauvaises) pratiques de web-performance et les outils pouvant améliorer votre code."
        time: "14h00"
    - name: "Pierre Rust"
      company: "Pierre Rust (Orange)"
      speakers:
        - name: "Pierre Rust"
          ref: "pierre"
          photo: "/img/speakers/pierre.jpg"
      presentation:
        title: "Outils d\'empreinte carbone des cloud public : comparer des pommes et des oranges"
        description: "L\'hébergement, et en particulier les data-centers, a un impact environnemental, mais on ne sait généralement pas estimer combien il représente sur nos projets. Depuis quelques mois, tous les grands fournisseurs de cloud public vous proposent des outils pour estimer le CO2 émis par les ressources cloud que vous utilisez. Malheureusement, il n\'existe pas de méthodologie commune pour ces estimations et chaque acteur compte un peu ce qu\'il veut ! Venez voir ce qui se cache derrières les \"calculettes carbones\" de GCP, Azure et AWS, ce qu'ils prennent en compte et ce qu'ils négligent."
        time: "14h45"
    - name: "break"
      time: "15h30"
    - name: "Olivier Le Goaër"
      company: "Olivier Le Goaër (Université de Pau)"
      speakers:
        - name: "Olivier Le Goaër"
          ref: "olivier"
          photo: "/img/speakers/olivier.png"
      presentation:
        title: "ecoCode mobile: how green is your app?"
        description: "Tandis que de plus en plus d’acteurs s’intéressent à l’éco-conception des sites Web, peu de travaux se sont intéressés aux apps mobile alors que ces dernières représentent un défi environnemental encore plus gigantesque.

Mais comment former la future génération de développeurs mobile à l’écriture d’un code plus écologique ?

Pour tenter de répondre à cette question, cette présentation introduit un catalogue spécifique de code smells pour Android ainsi qu’un plugin SonarQube pour les faire respecter."
        time: "15h45"
    - name: "Olivier Ridoux"
      company: "Olivier Ridoux (IRISA)"
      speakers:
        - name: "Olivier Ridoux"
          ref: "olivier_ridoux"
          photo: "/img/speakers/olivier_ridoux.png"
      presentation:
        title: "Moins vite, moins haut, moins fort : une devise pour le Green IT"
        description: "Le Green IT est souvent abordé comme faire autant voire plus avec moins, c’est-à-dire éliminer les impacts qui ne seraient pas essentiels à la réalisation d’une fonctionnalité désirée.
Nous allons proposer de l’aborder comme faire délibérément moins, avec encore moins, c’est-à-dire éliminer les exigences, et donc les fonctionnalités, qui seraient les plus impactantes.
Nous présenterons des exemples concrets et d’autres encore imaginaires, mais pas improbables, à l’appui de la devise « Moins vite, moins haut, moins fort »"
        time: "16h30"
    - name: "Fin"
      time: "17h30"

